2025-07-23 23:21:56,381 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:21:56,383 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:22:32,589 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:34:33,679 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:34:33,681 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:35:17,185 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:35:19,400 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:35:19,401 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:36:01,164 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:36:18,577 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:36:18,579 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:37:38,528 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:37:40,796 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:37:40,797 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:39:44,024 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:44:26,416 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:44:26,418 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:44:45,083 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 23:48:19,568 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 23:48:19,571 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 23:48:44,428 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-24 01:45:13,139 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-24 01:45:13,852 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-24 01:46:22,285 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 377, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-24 01:46:22,340 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 377, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-24 01:46:29,951 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-24T08:46:29.951182
2025-07-24 01:54:51,288 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-24 01:55:45,932 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-24 01:55:45,935 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-24 01:56:51,602 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-24 02:06:41,340 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-24 02:06:41,344 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-24 02:08:15,241 - INFO - app.core.security - [Redis] Connection closed successfully.
